-- Anonboard initial schema migration
-- Generated by: drizzle-kit generate (SQLite/D1)
-- Apply with: wrangler d1 execute DB --local --file=drizzle/0000_init.sql
--             wrangler d1 execute DB --file=drizzle/0000_init.sql (remote)

CREATE TABLE IF NOT EXISTS `identities` (
  `id` text PRIMARY KEY NOT NULL,
  `code_hash` text NOT NULL UNIQUE,
  `created_at` integer NOT NULL,
  `last_seen_at` integer NOT NULL
);

CREATE INDEX IF NOT EXISTS `identities_code_hash_idx` ON `identities` (`code_hash`);

CREATE TABLE IF NOT EXISTS `spaces` (
  `id` text PRIMARY KEY NOT NULL,
  `slug` text NOT NULL UNIQUE,
  `title` text NOT NULL,
  `description` text NOT NULL DEFAULT '',
  `is_general` integer NOT NULL DEFAULT 0,
  `creator_id` text REFERENCES `identities`(`id`),
  `created_at` integer NOT NULL
);

CREATE INDEX IF NOT EXISTS `spaces_slug_idx` ON `spaces` (`slug`);

CREATE TABLE IF NOT EXISTS `memberships` (
  `identity_id` text NOT NULL REFERENCES `identities`(`id`),
  `space_id` text NOT NULL REFERENCES `spaces`(`id`),
  `role` text NOT NULL DEFAULT 'member',
  `joined_at` integer NOT NULL,
  PRIMARY KEY (`identity_id`, `space_id`)
);

CREATE TABLE IF NOT EXISTS `posts` (
  `id` text PRIMARY KEY NOT NULL,
  `space_id` text NOT NULL REFERENCES `spaces`(`id`),
  `identity_id` text NOT NULL REFERENCES `identities`(`id`),
  `parent_post_id` text,
  `body` text NOT NULL,
  `created_at` integer NOT NULL,
  `deleted_at` integer
);

CREATE INDEX IF NOT EXISTS `posts_space_id_idx` ON `posts` (`space_id`);
CREATE INDEX IF NOT EXISTS `posts_created_at_idx` ON `posts` (`created_at`);

CREATE TABLE IF NOT EXISTS `reports` (
  `id` text PRIMARY KEY NOT NULL,
  `post_id` text NOT NULL REFERENCES `posts`(`id`),
  `reporter_id` text NOT NULL REFERENCES `identities`(`id`),
  `reason` text NOT NULL,
  `status` text NOT NULL DEFAULT 'pending',
  `created_at` integer NOT NULL
);
